### PR TITLE
bump bounds

### PR DESCRIPTION
**Pull request by sorki**
Allows
- bytestring 0.12
- containers 0.7
- mtl 2.3
- time 1.12
- unix 2.8
- optparse-applicative 0.18

Tested to build with GHC 9.4.7

### CODE REVIEW

**Comment by sorki** [comment]
This actually needs changes because of unix. I've tested the build on NixOS which didn't pull the most recent version. Will tackle CI as well. If you stumble on this let me know which versions of the older GHCs you would like to support.

**Comment by sorki** [comment]
All good now. I've added GHCs from 8.10 to 9.6 (9.8 needs work as it warns about `head` hehe). The CI now passes https://github.com/sorki/ircbot/actions/runs/7015362446 and will work here as well after merging (might need enabling in repo settings).

**Comment by sorki** [comment]
With the CI, I'm confident maintaining this and taking care of Hackage releases if you want.

**Comment by stepcut** [comment]
I can not upload this to hackage due to the use of the `-Werror` flag.

I think `-Werror` needs to be removed or put  behind a flag that is `False` by default.

**Comment by sorki** [comment]
How come? What's the response you get? I'll fix it tho!

**Comment by stepcut** [comment]
When I try `cabal upload` it fails with,

```
http code 400
Error: Invalid package

'ghc-options: -Werror' makes the package easy to break with future GHC
versions because new GHC versions often add new warnings. Alternatively, if
you want to use this, make it conditional based on a Cabal configuration flag
(with 'manual: True' and 'default: False') and enable that flag during
development.
```

**Comment by sorki** [comment]
Interesting (and new to me)! Fixed in #10

**Pull request merged**
