### PR TITLE
Simplified runner, demo refactor

### PR DESCRIPTION
**Pull request by sorki**
Also a bit of Nix refactoring, enabled warnings (which calls for one more pass thru code I'll probably do as well as next PR).

Regarding 
```
  case hasStdin of
    True -> Control.Monad.forever $ Control.Concurrent.threadDelay 1000000000
```
it indeed isn't a problem when running as a service and I would say mostly useful for testing.

### CODE REVIEW

**Comment by sorki** [comment]
This is how options look like now 
```
cabal run ircbot-demo -- \
  --server irc.example-network.org \
  --nick ircbot \
  --username ircbot \
  --hostname ircbot.example.org \
  --realname "ircbot" \
  --burst-length 2 \
  --delay-ms 1000000 \
  "#bottest"
```

(maybe add this as an example somewhere?)

**Comment by stepcut** [comment]
It seems this breaks on older versions of `base` because `<>` needs to be imported explicitly?

**Comment by sorki** [comment]
Oh, yes sorry - I've only tested with GHC8.10. 

As per `optparse-applicative` README
```
import Data.Semigroup ((<>))
```

will fix!

**Comment by stepcut** [comment]
If you want hackage upload permissions, I'll need your hackage username. Not sure if you have one yet..

**Comment by sorki** [comment]
Thanks for the invite! I don't mind - would still prefer to go thru pull requests for second pair of eyes but increasing bus factor is always a good idea. My hackage profile is https://hackage.haskell.org/user/srk

Which GHC versions would you like to support?

I've realized that using non-default `haskell.packages.ghc8101` is not the greatest idea when contributing new code due to possible breakage for older and the default set so I'll test with these as well. Most of the time I contribute fixes for "unstable" one so using that as my systems default.

I'm working on a CI for Nix projects and `ircbot` is one of the integral parts of it now so it will get lots of testing, hopefully the CI can test itself at some point and act as CI for the projects it is built upon.

**Pull request merged**
