### PR TITLE
Warnings, runDemo script, ci.nix

### PR DESCRIPTION
**Pull request by sorki**
- semigroups fix
- pruning warnings
- demo runner example
- `ci.nix` with few GHC versions I was quickly able to test with.

### CODE REVIEW

**Comment by stepcut** [comment]
I've restored the github support for showing the travis-ci checks. Looks like you removed an `import Data.Monoid(<>)` which is causing old GHCs to fail.

**Comment by sorki** [comment]
Thanks, tried to avoid that but two monoids slipped. Also added conditionals for GHC7.10 (semigroups and -Wunused-packages caused problems).

**Comment by stepcut** [comment]
Should I upload this to hackage, or do you have more changes coming soon?

**Comment by sorki** [comment]
Go for it. Should be all for now.

**Pull request merged**
